name: Deweb uploader

on:
    push:
        branches: [main]

jobs:
    deweb:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                network: [buildnet, mainnet]
            fail-fast: false
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "npm"
                  cache-dependency-path: ./package-lock.json

            - name: Install
              run: npm ci
              working-directory: ./

            - name: Build
              run: npm run build
              working-directory: ./

            - name: Deploy to Massa DeWeb (${{ matrix.network }})
              id: deploy
              uses: massalabs/deweb-gh-action@v0.1.0
              with:
                  config_file: ./deweb_cli_config.${{ matrix.network }}.json
                  source_folder: ./dist
              env:
                  MASSA_DEWEB_SECRET_KEY: ${{ matrix.network == 'buildnet' && secrets.PRIVATE_KEY || secrets.MASSA_DEWEB_MAINNET_PKEY }}

            - name: Get deployed website address
              run: |
                  echo "Deployed ${ matrix.network } website address: ${{ steps.deploy.outputs.deployed-website }}"
